# Generated by Django 3.1.4 on 2020-12-16 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(help_text='Id del post', max_length=250, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, help_text='Texto de la publicacion', max_length=350, null=True)),
                ('hashTags', models.CharField(blank=True, help_text='Tags de la publicacion', max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
