# Generated by Django 3.1.4 on 2020-12-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='to_network',
            field=models.CharField(default='Native', max_length=65),
        ),
    ]
