# Generated by Django 3.1.4 on 2020-12-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_to_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='to_network',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPage',
        ),
    ]
