# Generated by Django 3.1.4 on 2020-12-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201218_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageProfile',
        ),
    ]
