# Generated by Django 3.1.4 on 2020-12-21 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_post_postdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenType', models.CharField(blank=True, max_length=100, null=True)),
                ('contentUrl', models.URLField(blank=True, null=True)),
                ('text', models.CharField(max_length=250)),
                ('postCommendDate', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='post.post')),
            ],
        ),
    ]
