# Generated by Django 3.1.4 on 2020-12-21 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coments', '0002_coment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenType', models.CharField(blank=True, max_length=100, null=True)),
                ('contentUrl', models.URLField(blank=True, null=True)),
                ('text', models.CharField(max_length=250)),
                ('postCommendDate', models.DateTimeField(auto_now_add=True)),
                ('coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coments.coment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
